services:
  mysql:
    image: mysql:8
    container_name: metamapa-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Root123456
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - metamapa-net
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  core:
    build: ./core
    image: metamapa-core
    container_name: metamapa-core
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/core?serverTimezone=America/Argentina/Buenos_Aires
      JDBC_USER: root
      JDBC_PASS: Root123456
      CargadorDinamico: http://cargador-dinamico:8083/cargadorDinamico
      CargadorProxy: http://cargador-proxy:8084/cargadorProxy
      CargadorEstatico: http://cargador-estatica:8085/cargadorEstatico
    networks:
      - metamapa-net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:8081/ > /dev/null 2>&1 || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 45s

  cargador-dinamico:
    build: ./cargadorDinamica
    image: cargador-dinamica
    container_name: cargador-dinamica
    restart: unless-stopped
    depends_on:
      - mysql
      - core
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cargador_dinamica?serverTimezone=America/Argentina/Buenos_Aires
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root123456

      METAMAPA_API_BASE_URL: http://core:8081/core/api/public
      METAMAPA_API_ADMIN_BASE_URL: http://core:8081/core/api/admin
    networks:
      - metamapa-net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:8083/cargadorDinamico/health > /dev/null 2>&1 || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 45s

  cargador-estatica:
    build: ./cargadorEstatica
    image: cargador-estatica
    container_name: cargador-estatica
    restart: unless-stopped
    depends_on:
      - mysql
      - core
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cargador_estatica?serverTimezone=America/Argentina/Buenos_Aires
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root123456
      METAMAPA_API_BASE_URL: http://core:8081/core/api/public
    networks:
      - metamapa-net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:8085/cargadorEstatico/health > /dev/null 2>&1 || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 45s

  cargador-proxy:
    build: ./cargadorProxy
    image: cargador-proxy
    container_name: cargador-proxy
    restart: unless-stopped
    depends_on:
      - mysql
      - core
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cargador_proxy?serverTimezone=America/Argentina/Buenos_Aires
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root123456

      METAMAPA_API_BASE_URL: http://core:8081/core/api/public
    networks:
      - metamapa-net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:8084/cargadorProxy/health > /dev/null 2>&1 || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 45s

  servicio-estadisticas:
    build: ./servicioEstadisticas
    image: servicio-estadisticas
    container_name: servicio-estadisticas
    restart: unless-stopped
    depends_on:
      - mysql
      - core
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/core?serverTimezone=America/Argentina/Buenos_Aires
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root123456

      METAMAPA_API_BASE_URL: http://core:8081/core/api/public
    networks:
      - metamapa-net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:8090/servicioEstadisticas/health > /dev/null 2>&1 || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 45s

  prometheus:
    image: prom/prometheus:latest
    container_name: metamapa-prometheus
    restart: unless-stopped
    depends_on:
      - core
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - metamapa-net

  grafana:
    image: grafana/grafana:latest
    container_name: metamapa-grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Root123456
      - GF_SERVER_ROOT_URL=http://3.16.160.73/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - metamapa-net


  metamapa-web:
    build: ./metamapaWeb
    image: metamapa-web
    container_name: metamapa-web
    restart: unless-stopped
    depends_on:
      - core
      - grafana
    environment:
      METAMAPA_API_BASE_URL: http://core:8081/core/api/public
      METAMAPA_API_ADMIN_BASE_URL: http://core:8081/core/api/admin
      METAMAPA_API_ESTADISTICAS_BASE_URL: http://servicio-estadisticas:8090/servicioEstadisticas
      APP_URL_GRAPHQL_PLAYGROUND: http://3.16.160.73:80/graphql
      APP_URL_GRAFANA_DASHBOARD: http://3.16.160.73:80/grafana
    networks:
      - metamapa-net

  nginx:
    image: nginx:1.27-alpine
    container_name: metamapa-nginx
    restart: unless-stopped
    depends_on:
      - metamapa-web
      - core
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - metamapa-net


networks:
  metamapa-net:

volumes:
  mysql_data:
  prometheus_data:
  grafana_data: