worker_processes auto;

events { worker_connections 1024; }

http {
  # -------- RATE LIMIT --------
  limit_req_zone $binary_remote_addr zone=global_rate:10m rate=10r/s;

  server {
    listen 80;

    # -------- WEB --------
    location / {
      limit_req zone=global_rate burst=20 nodelay;

      proxy_pass http://metamapa-web:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # -------- GRAPHQL --------
    location /graphql {
      limit_req zone=global_rate burst=10 nodelay;

      proxy_pass http://core:8081/playground;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # -------- Grafana --------
    location /grafana/ {
      limit_req zone=global_rate burst=10 nodelay;

      proxy_pass http://grafana:3000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
