CargadorDinamico = http://cargador-dinamica:8083/cargadorDinamico
CargadorProxy    = http://cargador-proxy:8084/cargadorProxy
CargadorEstatico = http://cargador-estatica:8085/cargadorEstatico
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{correlationId}] [%thread] %logger{36} - %msg%n

