CargadorDinamico = http://localhost:8082/cargadorDinamico/obtenerHechos
CargadorProxy = http://localhost:8080/cargadorProxy/obtenerHechos
CargadorEstatico = http://localhost:8080/cargadorEstatico/obtenerHechos